### ISSUE TITLE
Broken Installation (Mate/Gnome)

### ISSUE THREAD

**Issue by PeKron** [Antergos/Cnchi#1138]
**Describe the bug**
Tried to install Antergos with Mate and got the error message in the first screenshot.
After i switched to gnome it worked fine. A day later I cant install Gnome either, fails with error message in the second screenshot.

**Expected behavior**
Working Installation

**Screenshots**
![photo_2019-03-26_18-00-50](https://user-images.githubusercontent.com/48960821/55017483-1cc69600-4ff1-11e9-9e61-4d9345329d88.jpg)

![photo_2019-03-26_17-59-08](https://user-images.githubusercontent.com/48960821/55017379-e38e2600-4ff0-11e9-89be-8cce409c7e41.jpg)

**Comment by Mikopet** [comment]
I have the same with deepin
`Cannot find these packages: thermald, qt5-styleplugins`

**Comment by Yoshi2889** [comment]
@lots0logs @karasu can we get some input here? There are many users with broken installers right now. Also at #1139

**Comment by karasu** [comment]
thermald has been moved to AUR. I've fixed Cnchi installer, but until new release, energy feature will be broken. The other qt5-styleplugins issue has been also fixed. Thanks!

**Comment by PeKron** [comment]
Problem is still there, antergos installation is broken because of mate-mint-menu (if you choose mate).
