### ISSUE TITLE
Error "can't create download package list"

### ISSUE THREAD

**Issue by sinayion** [Antergos/Cnchi#282]
Cnchi version: 0.8.7-1
Iso: antergos-2015.04.12-x86_64
Region/locale: en-US

After the step with user details, I get the error: "can't create download package list". All optional checkboxes were selected (AUR, Firefox, etc.)

The log shows the following pac errors a few times:
 - "returning error 6 from alpm_db_get_pkg: wrong or NULL argument passed"
 - "returning error 6 from alpm_db_get_group: wrong or NULL argument passed"

Also:
 - "ERROR: Can't find these packages:   "
 - An error about creating a metalink for a package named " " (blank space)

**Comment by karasu** [comment]
@sinayion , thanks for reporting.
What DE did you choose?
It looks like some package is missing. Maybe you got unlucky and you where using a non updated mirror
If you still have the log, copy it to a gist or pastebin and reference it here please.

**Comment by sinayion** [comment]
- KDE4
I just noticed that if I install with only Bluetooth Support & Printing Support checked (the defaults), it works. Going to narrow it down to the offending group in a bit.

**Comment by sinayion** [comment]
Argh, I need to head to bed. But it looks like it's one of:
 - Libreoffice
 - Firefox
 - Extra truetype fonts

**Comment by karasu** [comment]
Don't worry @sinayion , narrowing to that is going to be very useful, thanks.

**Comment by jasuka** [comment]
I have the same problem. I chose all packages except simple firewall. Cinnamon as desktop.

cnchi-dev log here: http://pastebin.com/bhZDbqgx

**Comment by jasuka** [comment]
Did some testing and enabling LibreOffice causes the problem for me.

**Comment by karasu** [comment]
Thanks. We'll look into it asap.

**Comment by roadev** [comment]
Then, for KDE4 only the defaults? (only Bluetooth Support & Printing Support checked)

**Comment by karasu** [comment]
Hi,

A wrong packages.xml file was being used by the installer. It should be ok now. I'll wait for your confirmation before closing this issue.

**Comment by karasu** [comment]
Oh, and this is, in fact, a duplicate of issue #283

**Comment by Sqwrly** [comment]
I'm trying to install on a T450S right now and I'm having this issue.

**Comment by karasu** [comment]
Did you choose libreoffice? It's broken atm.

**Comment by Sqwrly** [comment]
I did, but I took your comment of "It should be ok now." as it being fixed. :) I guess not.

**Comment by karasu** [comment]
I'm afraid it is not...

El dilluns, 13 abril de 2015, Sqwrly <notifications@github.com> va escriure:

> I did, but I took your comment of "It should be ok now." as it being
> fixed. :) I guess not.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Antergos/Cnchi/issues/282#issuecomment-92496016>.
>


-- 
Enviat amb el meu Iphone

**Comment by lots0logs** [comment]
FIxed with 51bb5b54239d54f15b033149a52f4bf3579c6c10

**Comment by Tafhim** [comment]
Just for anyone still facing this, this is now happening for the Flash plugin. I checked the log and unchecked the package on my subsequent try and it's working now.

**Comment by karasu** [comment]
fixed by https://github.com/Antergos/Cnchi/commit/ce521832dfd137843f0b0bdd4f80c38070c69102

**Comment by SJOwl** [comment]
I've faced up with the same problem when chose all packages. 
Then chose only Kernel, Printing Support, AUR, Chromium and Fonts.  
It's working now

**Comment by saterHATER** [comment]
Broken in 0.14.72
Desktop: Gnome
Packages: none

This is potentially just network restrictions in my case.

**Comment by fgallaire** [comment]
Same issue when selecting Deepin as desktop with Antergos 18.1

error 957276

2018-01-31 06:40:20 [ERROR] metalink.py(132) create(): Can't resolve these dependencies: deepin-artwork-themes
