### ISSUE TITLE
Cannot get through entire install.

### ISSUE THREAD

**Issue by skloeckner-inc** [Antergos/Cnchi#913]
**Describe the bug**
I get through the install far enough until I get past the mirror selection, then I get "Cannot create download package list(metalinks)"
No error code is given, however I do have log files below.

**To Reproduce**
Using cnchi 0.14.426
1. Select English/US for everything
2. Gnome desktop
3. Left Feature selection
4. Let cnchi decide on mirrors(I've also tried to modify them)
5. Tried both using ZFS and just a regular ext4 install

**Screenshots**

/tmp/cnchi.log
~~~~
2018-07-18 00:35:06 [WARNING] cnchi.py(235) setup_logging(): No module named 'bugsnag'
2018-07-18 00:35:06 [INFO] cnchi.py(271) check_gtk_version(): Using GTK v3.22.30
2018-07-18 00:35:06 [INFO] cnchi.py(283) check_pyalpm_version(): Using pyalpm v0.8 as interface to libalpm v11.0.0
2018-07-18 00:35:06 [DEBUG] cnchi.py(310) check_iso_version(): Running from ISO version 18.7
2018-07-18 00:35:06 [INFO] main_window.py(91) __init__(): Cnchi installer version 0.14.426
2018-07-18 00:35:06 [DEBUG] main_window.py(119) __init__(): Cnchi will use '/var/cache/pacman/pkg' as a source for cached xz packages
2018-07-18 00:35:06 [DEBUG] gtkbasebox.py(61) __init__(): Loading 'welcome' screen
2018-07-18 00:35:06 [INFO] main_window.py(326) header_for_all_callback(): fired!
2018-07-18 00:35:10 [DEBUG] gtkbasebox.py(61) __init__(): Loading 'language' screen
2018-07-18 00:35:10 [DEBUG] gtkbasebox.py(61) __init__(): Loading 'check' screen
2018-07-18 00:35:10 [DEBUG] gtkbasebox.py(61) __init__(): Loading 'location' screen
2018-07-18 00:35:10 [DEBUG] gtkbasebox.py(61) __init__(): Loading 'mirrors' screen
2018-07-18 00:35:10 [DEBUG] mirrors.py(177) load_mirrors(): http://arch.mirror.square-r00t.net/$repo/os/$arch
2018-07-18 00:35:10 [DEBUG] mirrors.py(177) load_mirrors(): https://arch.mirror.square-r00t.net/$repo/os/$arch
2018-07-18 00:35:10 [DEBUG] mirrors.py(177) load_mirrors(): http://archlinux.polymorf.fr/$repo/os/$arch
2018-07-18 00:35:10 [DEBUG] mirrors.py(177) load_mirrors(): http://mirror.ubrco.de/archlinux/$repo/os/$arch
2018-07-18 00:35:10 [DEBUG] mirrors.py(177) load_mirrors(): http://mirror.dkm.cz/archlinux/$repo/os/$arch
2018-07-18 00:35:10 [DEBUG] mirrors.py(177) load_mirrors(): http://arch.jensgutermuth.de/$repo/os/$arch
2018-07-18 00:35:10 [DEBUG] mirrors.py(177) load_mirrors(): http://mirrors.antergos.com/$repo/$arch
2018-07-18 00:35:10 [DEBUG] mirrors.py(177) load_mirrors(): http://repo.antergos.info/$repo/$arch
2018-07-18 00:35:10 [DEBUG] mirrors.py(177) load_mirrors(): http://repo.antergos.info/$repo/$arch
2018-07-18 00:35:10 [DEBUG] mirrors.py(177) load_mirrors(): http://mirror.bjtu.edu.cn/cinnarch/$repo/$arch
2018-07-18 00:35:10 [DEBUG] mirrors.py(177) load_mirrors(): http://cinnarch.polymorf.fr/$repo/$arch
2018-07-18 00:35:10 [DEBUG] mirrors.py(177) load_mirrors(): http://mirror.finn.lu/$repo/$arch
2018-07-18 00:35:10 [DEBUG] gtkbasebox.py(61) __init__(): Loading 'timezone' screen
2018-07-18 00:35:10 [DEBUG] gtkbasebox.py(61) __init__(): Loading 'keymap' screen
2018-07-18 00:35:10 [DEBUG] gtkbasebox.py(61) __init__(): Loading 'desktop' screen
2018-07-18 00:35:10 [DEBUG] gtkbasebox.py(61) __init__(): Loading 'features' screen
2018-07-18 00:35:10 [DEBUG] gtkbasebox.py(61) __init__(): Loading 'ask' screen
2018-07-18 00:35:10 [DEBUG] ask.py(88) load_zfs(): ZFS kernel module loaded successfully.
2018-07-18 00:35:10 [DEBUG] gtkbasebox.py(61) __init__(): Loading 'automatic' screen
2018-07-18 00:35:10 [DEBUG] gtkbasebox.py(61) __init__(): Loading 'advanced' screen
2018-07-18 00:35:10 [DEBUG] gtkbasebox.py(61) __init__(): Loading 'zfs' screen
2018-07-18 00:35:10 [DEBUG] gtkbasebox.py(61) __init__(): Loading 'summary' screen
2018-07-18 00:35:10 [DEBUG] gtkbasebox.py(61) __init__(): Loading 'user_info' screen
2018-07-18 00:35:10 [DEBUG] gtkbasebox.py(61) __init__(): Loading 'slides' screen
2018-07-18 00:35:11 [DEBUG] timezone.py(315) run(): A working network connection has been detected.
2018-07-18 00:35:11 [DEBUG] timezone.py(325) run(): We have connection. Let's get our timezone
2018-07-18 00:35:12 [DEBUG] timezone.py(348) run(): Timezone (latitude 33.6748, longitude -117.9089) detected.
2018-07-18 00:35:12 [DEBUG] language.py(201) store_values(): language_name: English
2018-07-18 00:35:12 [DEBUG] language.py(202) store_values(): language_code: en
2018-07-18 00:35:13 [WARNING] extra.py(393) get_prop(): org.freedesktop.DBus.Error.InvalidArgs: No such interface '/org/freedesktop/UPower'
2018-07-18 00:35:13 [WARNING] check.py(174) on_battery(): Cannot read /org/freedesktop/UPower/OnBattery dbus property
2018-07-18 00:35:13 [DEBUG] updater.py(76) __init__(): Cannot not find /usr/share/cnchi/update.info file. Cnchi will not be able to update itself.
2018-07-18 00:35:14 [INFO] check.py(232) store_values(): We have Internet connection.
2018-07-18 00:35:14 [INFO] check.py(233) store_values(): We're connected to a power source.
2018-07-18 00:35:14 [INFO] check.py(234) store_values(): We have enough disk space.
2018-07-18 00:35:14 [DEBUG] connectionpool.py(205) _new_conn(): Starting new HTTP connection (1): build.antergos.com:80
2018-07-18 00:35:14 [DEBUG] connectionpool.py(393) _make_request(): http://build.antergos.com:80 "GET /hook?cnchi=2580656b5c7be34e4144a3129a95e421 HTTP/1.1" 301 None
2018-07-18 00:35:14 [DEBUG] connectionpool.py(393) _make_request(): http://build.antergos.com:80 "GET /api/hook?cnchi=2580656b5c7be34e4144a3129a95e421 HTTP/1.1" 200 None
2018-07-18 00:35:18 [DEBUG] location.py(263) store_values(): Selected location: English (US), United States
2018-07-18 00:35:18 [DEBUG] location.py(281) store_values(): Selected country name: United States
2018-07-18 00:35:18 [DEBUG] location.py(282) store_values(): Selected country code: us
2018-07-18 00:35:18 [INFO] timezone.py(112) on_location_changed(): Location changed to : America/Los_Angeles
2018-07-18 00:35:20 [DEBUG] timezone.py(231) log_location(): timezone human zone: Los Angeles
2018-07-18 00:35:20 [DEBUG] timezone.py(232) log_location(): timezone country: US
2018-07-18 00:35:20 [DEBUG] timezone.py(233) log_location(): timezone zone: America/Los_Angeles
2018-07-18 00:35:20 [DEBUG] timezone.py(234) log_location(): timezone human country: United States
2018-07-18 00:35:20 [DEBUG] timezone.py(237) log_location(): timezone comment: Pacific
2018-07-18 00:35:20 [DEBUG] timezone.py(240) log_location(): timezone latitude: 34.0308
2018-07-18 00:35:20 [DEBUG] timezone.py(243) log_location(): timezone longitude: -118.1434
2018-07-18 00:35:20 [DEBUG] timezone.py(278) store_values(): Cnchi will setup network time using systemd-timesyncd
2018-07-18 00:35:20 [DEBUG] keymap.py(307) set_keymap(): Set keyboard to 'English (US)' (us)
2018-07-18 00:35:46 [DEBUG] keymap.py(307) set_keymap(): Set keyboard to 'English (US)' (us)
2018-07-18 00:35:47 [INFO] desktop.py(232) store_values(): Cnchi will install Antergos with the 'gnome' desktop
2018-07-18 00:35:48 [DEBUG] features.py(203) fill_listbox(): Removing proprietary graphic drivers feature.
2018-07-18 00:35:57 [DEBUG] features.py(393) store_switches(): Feature 'aur' has been selected
2018-07-18 00:35:57 [DEBUG] features.py(393) store_switches(): Feature 'cups' has been selected
2018-07-18 00:35:57 [DEBUG] features.py(393) store_switches(): Feature 'chromium' has been selected
2018-07-18 00:36:44 [INFO] ask.py(448) store_values(): Antergos will be installed using ZFS
2018-07-18 00:36:44 [INFO] ask.py(453) store_values(): Antergos will be installed using a separate /home volume.
2018-07-18 00:36:54 [DEBUG] select_packages.py(105) create_package_list(): Refreshing pacman databases...
2018-07-18 00:36:54 [DEBUG] pac.py(122) initialize_alpm(): ALPM initialised with root dir / and db path /var/lib/pacman
2018-07-18 00:36:54 [DEBUG] pac.py(98) __init__(): ALPM repository database order is: ['antergos', 'core', 'extra', 'community', 'multilib']
2018-07-18 00:36:55 [INFO] slides.py(276) manage_events_from_cb_queue(): Updating antergos database
2018-07-18 00:36:57 [INFO] slides.py(276) manage_events_from_cb_queue(): Updating core database
2018-07-18 00:36:57 [INFO] slides.py(276) manage_events_from_cb_queue(): Updating extra database
2018-07-18 00:37:00 [DEBUG] select_packages.py(107) create_package_list(): Pacman ready
2018-07-18 00:37:00 [DEBUG] select_packages.py(109) create_package_list(): Selecting packages...
2018-07-18 00:37:00 [DEBUG] select_packages.py(204) select_packages(): Getting url https://raw.githubusercontent.com/Antergos/Cnchi/master/data/packages.xml...
2018-07-18 00:37:00 [DEBUG] connectionpool.py(823) _new_conn(): Starting new HTTPS connection (1): raw.githubusercontent.com:443
2018-07-18 00:37:00 [DEBUG] connectionpool.py(393) _make_request(): https://raw.githubusercontent.com:443 "GET /Antergos/Cnchi/master/data/packages.xml HTTP/1.1" 200 2520
2018-07-18 00:37:00 [DEBUG] select_packages.py(220) select_packages(): Loading xml data from server...
2018-07-18 00:37:00 [DEBUG] select_packages.py(243) select_packages(): Adding gnome desktop packages
2018-07-18 00:37:00 [INFO] slides.py(276) manage_events_from_cb_queue(): Updating community database
2018-07-18 00:37:00 [INFO] slides.py(276) manage_events_from_cb_queue(): Updating multilib database
2018-07-18 00:37:00 [INFO] slides.py(276) manage_events_from_cb_queue(): Getting package list...
2018-07-18 00:37:00 [DEBUG] hardware.py(256) __init__(): Cnchi will test 18 drivers for 24 hardware devices
2018-07-18 00:37:00 [DEBUG] hardware.py(270) __init__(): Driver Intel915 is needed by (0x03, 0x8086, 0x5916)
2018-07-18 00:37:00 [DEBUG] hardware.py(270) __init__(): Driver VesaFB is needed by (0x03, 0x8086, 0x5916)
2018-07-18 00:37:00 [DEBUG] select_packages.py(274) select_packages(): Hardware module detected these drivers: ['Intel915']
2018-07-18 00:37:00 [DEBUG] select_packages.py(281) select_packages(): Hardware module added these packages: libva-intel-driver, xf86-video-intel, lib32-mesa
2018-07-18 00:37:00 [DEBUG] select_packages.py(304) select_packages(): Adding filesystem packages
2018-07-18 00:37:00 [DEBUG] select_packages.py(311) select_packages(): Adding zfs packages
2018-07-18 00:37:00 [DEBUG] select_packages.py(332) select_packages(): Adding 'grub2' bootloader packages
2018-07-18 00:37:00 [DEBUG] select_packages.py(342) select_packages(): Check for user desired features and add them to our installation
2018-07-18 00:37:00 [DEBUG] select_packages.py(388) add_features_packages(): Adding packages for 'aur' feature.
2018-07-18 00:37:00 [DEBUG] select_packages.py(394) add_features_packages(): Selecting package aurman for feature aur
2018-07-18 00:37:00 [DEBUG] select_packages.py(394) add_features_packages(): Selecting package bzr for feature aur
2018-07-18 00:37:00 [DEBUG] select_packages.py(394) add_features_packages(): Selecting package cmake for feature aur
2018-07-18 00:37:00 [DEBUG] select_packages.py(394) add_features_packages(): Selecting package git for feature aur
2018-07-18 00:37:00 [DEBUG] select_packages.py(394) add_features_packages(): Selecting package yaourt for feature aur
2018-07-18 00:37:00 [DEBUG] select_packages.py(388) add_features_packages(): Adding packages for 'cups' feature.
2018-07-18 00:37:00 [DEBUG] select_packages.py(394) add_features_packages(): Selecting package cups for feature cups
2018-07-18 00:37:00 [DEBUG] select_packages.py(394) add_features_packages(): Selecting package cups-pk-helper for feature cups
2018-07-18 00:37:00 [DEBUG] select_packages.py(394) add_features_packages(): Selecting package gsfonts for feature cups
2018-07-18 00:37:00 [DEBUG] select_packages.py(394) add_features_packages(): Selecting package hplip for feature cups
2018-07-18 00:37:00 [DEBUG] select_packages.py(394) add_features_packages(): Selecting package system-config-printer for feature cups
2018-07-18 00:37:00 [DEBUG] select_packages.py(394) add_features_packages(): Selecting package python2-gnomekeyring for feature cups
2018-07-18 00:37:00 [DEBUG] select_packages.py(394) add_features_packages(): Selecting package splix for feature cups
2018-07-18 00:37:00 [DEBUG] select_packages.py(394) add_features_packages(): Selecting package python-pyqt5 for feature cups
2018-07-18 00:37:00 [DEBUG] select_packages.py(394) add_features_packages(): Selecting package python-gobject for feature cups
2018-07-18 00:37:00 [DEBUG] select_packages.py(388) add_features_packages(): Adding packages for 'chromium' feature.
2018-07-18 00:37:00 [DEBUG] select_packages.py(394) add_features_packages(): Selecting package chromium for feature chromium
2018-07-18 00:37:00 [DEBUG] select_packages.py(344) select_packages(): All features needed packages have been added
2018-07-18 00:37:00 [DEBUG] select_packages.py(361) select_packages(): Packages list: cryfs,unrar,antergos-keyring,gzip,cifs-utils,ipw2100-fw,base-devel,nilfs-utils,cmake,xfsprogs,htop,grub,antergos-gnome-meta,modemmanager,wpa_actiond,ipw2200-fw,reiserfsprogs,hplip,aurman,bash-completion,antergos-mirrorlist,acpid,networkmanager,screenfetch,sudo,bind-tools,alsa-utils,b43-fwcutter,xf86-video-intel,efibootmgr,bzr,spl,cups-pk-helper,exfat-utils,chromium,python2-gnomekeyring,zfs-utils,antergos-desktop-settings,system-config-printer,haveged,terminus-font,base,mlocate,antergos-midnight-timers,libva-intel-driver,yaourt,ntfs-3g,grub-zfs,usb_modeswitch,gsfonts,pkgfile,wget,intel-ucode,crda,e2fsprogs,net-tools,reflector,whois,wireless_tools,antergos-common-meta,nfs-utils,grub2-theme-antergos,git,python-gobject,btrfs-progs,unzip,splix,dosfstools,tar,lib32-mesa,dmraid,cups,openssh,jfsutils,os-prober,zfs,f2fs-tools,python-pyqt5,spl-utils
2018-07-18 00:37:00 [DEBUG] select_packages.py(111) create_package_list(): Packages selected
2018-07-18 00:37:00 [DEBUG] pac.py(122) initialize_alpm(): ALPM initialised with root dir / and db path /var/lib/pacman
2018-07-18 00:37:00 [DEBUG] pac.py(98) __init__(): ALPM repository database order is: ['antergos', 'core', 'extra', 'community', 'multilib']
2018-07-18 00:37:00 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:01 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:01 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:01 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:01 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:01 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:01 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:01 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:01 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:01 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:01 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:01 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:01 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:01 [INFO] slides.py(276) manage_events_from_cb_queue(): Creating the list of packages to download...
2018-07-18 00:37:01 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:01 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:01 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:01 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:01 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:01 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:01 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:01 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:01 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:01 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:02 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:02 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:02 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:02 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:02 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:02 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:02 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:02 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:02 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:02 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:02 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:02 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:02 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:02 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:02 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:02 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:02 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:02 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:02 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:02 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:02 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:02 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:02 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:02 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:02 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:02 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:02 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:02 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:02 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:02 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:02 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:02 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:02 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:02 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:02 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:02 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:02 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-18 00:37:03 [ERROR] metalink.py(132) create(): Can't resolve these dependencies: hunspell-es 
2018-07-18 00:37:03 [ERROR] download.py(150) create_metalinks_list(): Error creating metalink for package antergos-common-meta. Installation will stop
2018-07-18 00:37:03 [ERROR] download.py(182) create_metalinks_list(): Can't create download set. An exception of type InstallError occured. Arguments:
('Error creating metalink for package antergos-common-meta. Installation will stop',)
2018-07-18 00:37:03 [ERROR] process.py(130) run(): 'Cannot create download package list (metalinks).'
2018-07-18 00:37:03 [ERROR] process.py(135) run(): Traceback (most recent call last):
2018-07-18 00:37:03 [ERROR] process.py(135) run():   File "/usr/share/cnchi/src/installation/process.py", line 92, in run
    self.create_metalinks_list()
2018-07-18 00:37:03 [ERROR] process.py(135) run():   File "/usr/share/cnchi/src/installation/process.py", line 82, in create_metalinks_list
    raise misc.InstallError(txt)
2018-07-18 00:37:03 [ERROR] process.py(135) run(): misc.extra.InstallError: 'Cannot create download package list (metalinks).'
~~~~

**Comment by pserrano** [comment]
Same error for me, i'm checking repositories and i didn't found group cinnamon and hunspell-es (Only found packages like hunspell-es_es but i didn't find it this base package) I think that main error is from db and packages. You can make bypass for cinammon part, try to remove cinammon name on the array group packages, but other error can be impossible to bypass.

**Comment by skloeckner-inc** [comment]
So, I upgraded my current system which was recently installed and I see hunspell-es was replaced with extra/hunspell-es_any

See below.

~~~~
$ sudo pacman -Syu
:: Synchronizing package databases...
 antergos                                                                                             162.0 KiB  52.7M/s 00:00 [#############################################################################] 100%
 core                                                                                                 130.8 KiB  0.00B/s 00:00 [#############################################################################] 100%
 extra                                                                                               1650.9 KiB  94.8M/s 00:00 [#############################################################################] 100%
 community                                                                                              4.5 MiB   104M/s 00:00 [#############################################################################] 100%
 multilib                                                                                             170.1 KiB  0.00B/s 00:00 [#############################################################################] 100%
:: Starting full system upgrade...
:: Replace hunspell-es with extra/hunspell-es_any? [Y/n] y
resolving dependencies...
looking for conflicting packages...

Packages (23) antergos-common-meta-1.2-1  appstream-glib-0.7.10-1  gnome-bluetooth-3.28.1-1  gnome-shell-3.28.3-1  gnupg-2.2.9-1  gnutls-3.5.19-1  guake-3.3.2-1  harfbuzz-1.8.4-1  harfbuzz-icu-1.8.4-1
              hunspell-es-1:2.3-1 [removal]  hunspell-es_any-1:2.3-2  imagemagick-7.0.8.7-1  libgdm-3.28.2+19+g161f3462-1  libmagick-7.0.8.7-1  libtiff-4.0.9-2  linux-lts-4.14.56-1  linux-lts-headers-4.14.56-1
              mutter-3.28.3-1  npth-1.6-1  pango-1.42.2-1  pciutils-3.6.1-1  pipewire-0.2.0-1  polari-3.28.1-1

Total Download Size:    84.10 MiB
Total Installed Size:  245.56 MiB
Net Upgrade Size:      -15.44 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
~~~~

**Comment by skloeckner-inc** [comment]
Looks like the install just works now. I finally got my ZFS on my laptop.

**Comment by karasu** [comment]
Fixed by https://github.com/Antergos/antergos-packages/commit/a5ab8f806ce7dd897a9b09f637e1fd1d39247d72

**Comment by KeAWang** [comment]
How do we integrate the bugfix into cnchi? I still can't install Antergos.

**Comment by karasu** [comment]
@KeAWang this was in fact a bug in a package, not in Cnchi itself, so nothing needs to be done here.
Just today we fixed another bug in the Deepin meta package. Did your installation fail trying to install Deepin? If not, which DE did you try to install?

**Comment by KeAWang** [comment]
I'm trying to install the Deepin desktop environment and I'm still running into the same errors. 

My /tmp/cnchi.log shows 
```
2018-07-22 20:11:55 [WARNING] cnchi.py(235) setup_logging(): No module named 'bugsnag'
2018-07-22 20:11:55 [INFO] cnchi.py(271) check_gtk_version(): Using GTK v3.22.30
2018-07-22 20:11:55 [INFO] cnchi.py(283) check_pyalpm_version(): Using pyalpm v0.8 as interface to libalpm v11.0.0
2018-07-22 20:11:55 [DEBUG] cnchi.py(310) check_iso_version(): Running from ISO version 18.7
2018-07-22 20:11:55 [DEBUG] cnchi.py(315) check_iso_version(): User's chromium cache deleted
2018-07-22 20:11:55 [DEBUG] cnchi.py(150) already_running(): File /tmp/.setup-running already exists.
2018-07-22 20:11:55 [INFO] cnchi.py(165) already_running(): Cnchi with pid '1211' already running.
2018-07-22 20:12:07 [DEBUG] keymap.py(307) set_keymap(): Set keyboard to 'English (US)' (us)
2018-07-22 20:12:09 [INFO] desktop.py(232) store_values(): Cnchi will install Antergos with the 'deepin' desktop
2018-07-22 20:12:09 [DEBUG] features.py(203) fill_listbox(): Removing proprietary graphic drivers feature.
2018-07-22 20:12:20 [DEBUG] features.py(393) store_switches(): Feature 'cups' has been selected
2018-07-22 20:12:20 [DEBUG] features.py(393) store_switches(): Feature 'aur' has been selected
2018-07-22 20:12:20 [DEBUG] features.py(393) store_switches(): Feature 'sshd' has been selected
2018-07-22 20:12:20 [DEBUG] features.py(393) store_switches(): Feature 'office' has been selected
2018-07-22 20:12:20 [DEBUG] features.py(393) store_switches(): Feature 'bluetooth' has been selected
2018-07-22 20:12:20 [DEBUG] features.py(393) store_switches(): Feature 'firewall' has been selected
2018-07-22 20:12:20 [DEBUG] features.py(393) store_switches(): Feature 'chromium' has been selected
2018-07-22 20:12:20 [DEBUG] features.py(393) store_switches(): Feature 'games' has been selected
2018-07-22 20:12:38 [DEBUG] fs_module.py(67) get_label(): Can't get partition /dev/nvme0n1p2 label (or it does not have any)
2018-07-22 20:12:38 [DEBUG] fs_module.py(67) get_label(): Can't get partition /dev/nvme0n1p3 label (or it does not have any)
2018-07-22 20:12:38 [DEBUG] fs_module.py(67) get_label(): Can't get partition /dev/nvme0n1p4 label (or it does not have any)
2018-07-22 20:12:38 [DEBUG] fs_module.py(67) get_label(): Can't get partition /dev/sda1 label (or it does not have any)
2018-07-22 20:12:50 [DEBUG] fs_module.py(67) get_label(): Can't get partition /dev/nvme0n1p3 label (or it does not have any)
2018-07-22 20:12:50 [DEBUG] fs_module.py(67) get_label(): Can't get partition /dev/nvme0n1p4 label (or it does not have any)
2018-07-22 20:12:50 [DEBUG] fs_module.py(67) get_label(): Can't get partition /dev/sda1 label (or it does not have any)
2018-07-22 20:13:00 [DEBUG] advanced.py(1277) on_partition_list_new_activate(): Creating a primary partition
2018-07-22 20:13:00 [DEBUG] fs_module.py(67) get_label(): Can't get partition /dev/nvme0n1p3 label (or it does not have any)
2018-07-22 20:13:00 [DEBUG] fs_module.py(67) get_label(): Can't get partition /dev/nvme0n1p4 label (or it does not have any)
2018-07-22 20:13:00 [WARNING] fs_module.py(104) get_type(): Error running ['lsblk', '/dev/nvme0n1p5', '-n', '-o', 'FSTYPE', '-l']: b''
2018-07-22 20:13:00 [DEBUG] fs_module.py(67) get_label(): Can't get partition /dev/sda1 label (or it does not have any)
2018-07-22 20:13:05 [INFO] advanced.py(2222) set_bootloader(): Antergos will install the bootloader grub2 in device /dev/nvme0n1
2018-07-22 20:13:05 [DEBUG] advanced.py(2176) get_changes(): Device /dev/nvme0n1p2 will be modified, relabeled, not formatted, mounted as /boot/efi and not encrypted.
2018-07-22 20:13:05 [DEBUG] advanced.py(2176) get_changes(): Device /dev/nvme0n1p5 will be created, relabeled, formatted, mounted as / and not encrypted.
2018-07-22 20:13:09 [DEBUG] select_packages.py(105) create_package_list(): Refreshing pacman databases...
2018-07-22 20:13:09 [DEBUG] pac.py(122) initialize_alpm(): ALPM initialised with root dir / and db path /var/lib/pacman
2018-07-22 20:13:09 [DEBUG] pac.py(98) __init__(): ALPM repository database order is: ['antergos', 'core', 'extra', 'community', 'multilib']
2018-07-22 20:13:11 [INFO] slides.py(276) manage_events_from_cb_queue(): Updating antergos database
2018-07-22 20:13:11 [INFO] slides.py(276) manage_events_from_cb_queue(): Updating core database
2018-07-22 20:13:11 [INFO] slides.py(276) manage_events_from_cb_queue(): Updating extra database
2018-07-22 20:13:11 [DEBUG] select_packages.py(107) create_package_list(): Pacman ready
2018-07-22 20:13:11 [DEBUG] select_packages.py(109) create_package_list(): Selecting packages...
2018-07-22 20:13:11 [DEBUG] select_packages.py(204) select_packages(): Getting url https://raw.githubusercontent.com/Antergos/Cnchi/master/data/packages.xml...
2018-07-22 20:13:11 [DEBUG] connectionpool.py(823) _new_conn(): Starting new HTTPS connection (1): raw.githubusercontent.com:443
2018-07-22 20:13:11 [DEBUG] connectionpool.py(393) _make_request(): https://raw.githubusercontent.com:443 "GET /Antergos/Cnchi/master/data/packages.xml HTTP/1.1" 200 2520
2018-07-22 20:13:11 [DEBUG] select_packages.py(220) select_packages(): Loading xml data from server...
2018-07-22 20:13:11 [DEBUG] select_packages.py(243) select_packages(): Adding deepin desktop packages
2018-07-22 20:13:11 [DEBUG] hardware.py(256) __init__(): Cnchi will test 18 drivers for 33 hardware devices
2018-07-22 20:13:11 [DEBUG] hardware.py(270) __init__(): Driver Nouveau is needed by (0x03, 0x10de, 0x1b06)
2018-07-22 20:13:11 [DEBUG] hardware.py(270) __init__(): Driver VesaFB is needed by (0x03, 0x10de, 0x1b06)
2018-07-22 20:13:11 [DEBUG] select_packages.py(274) select_packages(): Hardware module detected these drivers: ['Nouveau']
2018-07-22 20:13:11 [DEBUG] select_packages.py(281) select_packages(): Hardware module added these packages: mesa, lib32-mesa, xf86-video-nouveau
2018-07-22 20:13:11 [DEBUG] select_packages.py(304) select_packages(): Adding filesystem packages
2018-07-22 20:13:11 [DEBUG] select_packages.py(332) select_packages(): Adding 'grub2' bootloader packages
2018-07-22 20:13:11 [DEBUG] select_packages.py(342) select_packages(): Check for user desired features and add them to our installation
2018-07-22 20:13:11 [DEBUG] select_packages.py(388) add_features_packages(): Adding packages for 'aur' feature.
2018-07-22 20:13:11 [DEBUG] select_packages.py(394) add_features_packages(): Selecting package aurman for feature aur
2018-07-22 20:13:11 [DEBUG] select_packages.py(394) add_features_packages(): Selecting package bzr for feature aur
2018-07-22 20:13:11 [DEBUG] select_packages.py(394) add_features_packages(): Selecting package cmake for feature aur
2018-07-22 20:13:11 [DEBUG] select_packages.py(394) add_features_packages(): Selecting package git for feature aur
2018-07-22 20:13:11 [DEBUG] select_packages.py(394) add_features_packages(): Selecting package yaourt for feature aur
2018-07-22 20:13:11 [DEBUG] select_packages.py(388) add_features_packages(): Adding packages for 'bluetooth' feature.
2018-07-22 20:13:11 [DEBUG] select_packages.py(394) add_features_packages(): Selecting package bluez for feature bluetooth
2018-07-22 20:13:11 [DEBUG] select_packages.py(394) add_features_packages(): Selecting package bluez-utils for feature bluetooth
2018-07-22 20:13:11 [DEBUG] select_packages.py(394) add_features_packages(): Selecting package pulseaudio-bluetooth for feature bluetooth
2018-07-22 20:13:11 [DEBUG] select_packages.py(388) add_features_packages(): Adding packages for 'cups' feature.
2018-07-22 20:13:11 [DEBUG] select_packages.py(394) add_features_packages(): Selecting package cups for feature cups
2018-07-22 20:13:11 [DEBUG] select_packages.py(394) add_features_packages(): Selecting package cups-pk-helper for feature cups
2018-07-22 20:13:11 [DEBUG] select_packages.py(394) add_features_packages(): Selecting package gsfonts for feature cups
2018-07-22 20:13:11 [DEBUG] select_packages.py(394) add_features_packages(): Selecting package hplip for feature cups
2018-07-22 20:13:11 [DEBUG] select_packages.py(394) add_features_packages(): Selecting package system-config-printer for feature cups
2018-07-22 20:13:11 [DEBUG] select_packages.py(394) add_features_packages(): Selecting package python2-gnomekeyring for feature cups
2018-07-22 20:13:11 [DEBUG] select_packages.py(394) add_features_packages(): Selecting package splix for feature cups
2018-07-22 20:13:11 [DEBUG] select_packages.py(394) add_features_packages(): Selecting package python-pyqt5 for feature cups
2018-07-22 20:13:11 [DEBUG] select_packages.py(394) add_features_packages(): Selecting package python-gobject for feature cups
2018-07-22 20:13:11 [DEBUG] select_packages.py(388) add_features_packages(): Adding packages for 'chromium' feature.
2018-07-22 20:13:11 [DEBUG] select_packages.py(394) add_features_packages(): Selecting package chromium for feature chromium
2018-07-22 20:13:11 [DEBUG] select_packages.py(388) add_features_packages(): Adding packages for 'firewall' feature.
2018-07-22 20:13:11 [DEBUG] select_packages.py(394) add_features_packages(): Selecting package gufw for feature firewall
2018-07-22 20:13:11 [DEBUG] select_packages.py(394) add_features_packages(): Selecting package ufw for feature firewall
2018-07-22 20:13:11 [DEBUG] select_packages.py(388) add_features_packages(): Adding packages for 'games' feature.
2018-07-22 20:13:11 [DEBUG] select_packages.py(394) add_features_packages(): Selecting package steam-native-runtime for feature games
2018-07-22 20:13:11 [DEBUG] select_packages.py(394) add_features_packages(): Selecting package steam for feature games
2018-07-22 20:13:11 [DEBUG] select_packages.py(394) add_features_packages(): Selecting package playonlinux for feature games
2018-07-22 20:13:11 [DEBUG] select_packages.py(394) add_features_packages(): Selecting package lib32-libldap for feature games
2018-07-22 20:13:11 [DEBUG] select_packages.py(388) add_features_packages(): Adding packages for 'office' feature.
2018-07-22 20:13:11 [DEBUG] select_packages.py(394) add_features_packages(): Selecting package libreoffice-fresh for feature office
2018-07-22 20:13:11 [DEBUG] select_packages.py(388) add_features_packages(): Adding packages for 'sshd' feature.
2018-07-22 20:13:11 [DEBUG] select_packages.py(394) add_features_packages(): Selecting package openssh for feature sshd
2018-07-22 20:13:11 [DEBUG] select_packages.py(344) select_packages(): All features needed packages have been added
2018-07-22 20:13:11 [DEBUG] select_packages.py(356) select_packages(): Conflicts list: nvidia-340xx-lts, nvidia-ltsnvidia-utils, nvidia-304xx, nvidia-340xx, nvidia-304xx-lts, nvidia-libgl, bumblebee, nvidia, nvidia-304xx-utils, bbswitch, nvidia-340xx-utils, nvidia-settings, virtualgl
2018-07-22 20:13:11 [DEBUG] select_packages.py(361) select_packages(): Packages list: gzip,crda,pkgfile,sudo,grub,splix,bzr,nfs-utils,openssh,modemmanager,terminus-font,os-prober,pulseaudio-bluetooth,xf86-video-nouveau,reflector,cifs-utils,aurman,e2fsprogs,hplip,exfat-utils,jfsutils,antergos-keyring,dosfstools,b43-fwcutter,antergos-midnight-timers,f2fs-tools,nilfs-utils,system-config-printer,xfsprogs,base,steam,grub2-theme-antergos,reiserfsprogs,unrar,haveged,lib32-libldap,screenfetch,chromium,mesa,antergos-deepin-meta,python2-gnomekeyring,libreoffice-fresh,wget,cups,dmraid,cups-pk-helper,efibootmgr,gufw,ipw2200-fw,wireless_tools,cmake,bluez,ntfs-3g,python-gobject,mlocate,ufw,steam-native-runtime,base-devel,intel-ucode,playonlinux,antergos-desktop-settings,ipw2100-fw,acpid,unzip,tar,alsa-utils,python-pyqt5,net-tools,htop,networkmanager,antergos-mirrorlist,antergos-common-meta,usb_modeswitch,git,yaourt,lib32-mesa,wpa_actiond,bind-tools,btrfs-progs,bluez-utils,whois,gsfonts,cryfs,bash-completion
2018-07-22 20:13:11 [DEBUG] select_packages.py(111) create_package_list(): Packages selected
2018-07-22 20:13:11 [DEBUG] pac.py(122) initialize_alpm(): ALPM initialised with root dir / and db path /var/lib/pacman
2018-07-22 20:13:11 [DEBUG] pac.py(98) __init__(): ALPM repository database order is: ['antergos', 'core', 'extra', 'community', 'multilib']
2018-07-22 20:13:11 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-22 20:13:12 [INFO] slides.py(276) manage_events_from_cb_queue(): Updating community database
2018-07-22 20:13:12 [INFO] slides.py(276) manage_events_from_cb_queue(): Updating multilib database
2018-07-22 20:13:12 [INFO] slides.py(276) manage_events_from_cb_queue(): Getting package list...
2018-07-22 20:13:12 [INFO] slides.py(276) manage_events_from_cb_queue(): Creating the list of packages to download...
2018-07-22 20:13:12 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-22 20:13:12 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-22 20:13:12 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-22 20:13:12 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-22 20:13:12 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-22 20:13:13 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-22 20:13:13 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-22 20:13:13 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-22 20:13:13 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-22 20:13:13 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-22 20:13:13 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-22 20:13:13 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-22 20:13:13 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-22 20:13:13 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-22 20:13:13 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-22 20:13:13 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-22 20:13:13 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-22 20:13:13 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-22 20:13:13 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-22 20:13:13 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-22 20:13:13 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-22 20:13:13 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-22 20:13:13 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-22 20:13:13 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-22 20:13:13 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-22 20:13:13 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-22 20:13:13 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-22 20:13:13 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-22 20:13:13 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-22 20:13:13 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-22 20:13:13 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-22 20:13:13 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-22 20:13:13 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-22 20:13:13 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-22 20:13:13 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-22 20:13:13 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-22 20:13:13 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-22 20:13:14 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-22 20:13:14 [WARNING] metalink.py(342) build_download_queue(): Error reading group 'cinnamon' from the antergos repo db
2018-07-22 20:13:14 [ERROR] metalink.py(132) create(): Can't resolve these dependencies: deepin-help 
2018-07-22 20:13:14 [ERROR] download.py(150) create_metalinks_list(): Error creating metalink for package antergos-deepin-meta. Installation will stop
2018-07-22 20:13:14 [ERROR] download.py(182) create_metalinks_list(): Can't create download set. An exception of type InstallError occured. Arguments:
('Error creating metalink for package antergos-deepin-meta. Installation will stop',)
2018-07-22 20:13:14 [ERROR] process.py(130) run(): 'Cannot create download package list (metalinks).'
2018-07-22 20:13:14 [ERROR] process.py(135) run(): Traceback (most recent call last):
2018-07-22 20:13:14 [ERROR] process.py(135) run():   File "/usr/share/cnchi/src/installation/process.py", line 92, in run
    self.create_metalinks_list()
2018-07-22 20:13:14 [ERROR] process.py(135) run():   File "/usr/share/cnchi/src/installation/process.py", line 82, in create_metalinks_list
    raise misc.InstallError(txt)
2018-07-22 20:13:14 [ERROR] process.py(135) run(): misc.extra.InstallError: 'Cannot create download package list (metalinks).'
```

**Comment by karasu** [comment]
Yep, as I said, there was a problem with the antergos-deepin-meta package that has already been solved. Problem is that some mirrors take a bit to update themselves. On my end, my mirror is already updated, but it will depend on which mirror you're using. Anyway, as it is more than 24h that we updated that package, I'm confident that if you retry it will work now.

**Comment by BitPhinix** [comment]
It still doesn't work :( Same error as above.

**Comment by MyriaCore** [comment]
@BitPhinix I still got the same problem too, I raised it in issue #920
