### ISSUE TITLE
Cannot create download package list (metalinks)

### ISSUE THREAD

**Issue by lorenzopincinato** [Antergos/Cnchi#918]
**Problem**
Cannot create download package list (metalinks)
Error: None

**Steps To Reproduce**
1. Wait Cnchi updates
2. Select your region options
3. Select your partition options
4. Wait Cnchi rank the best mirrors
5. The error pops up when creating my user account

**Screenshot**
- [Cnchi 0.14.426](https://imgur.com/xJCkS4q)

**Log File**
- [/tmp/cnchi.log](https://gist.github.com/lorenzopincinato/fda317d9742508fa3f8f2f6d16e512c5)

**Additional context**
I selected Deepin Desktop, AUR, Bluetooth, Chromium and Printer

**Comment by karasu** [comment]
Thanks for reporting this. It's a problem with the deepin desktop depencencies. We'll fix this asap.

**Comment by karasu** [comment]
Fixed by https://github.com/Antergos/antergos-packages/commit/f7f12f9271ba3078fbd556722b2d984afd886ffe

Please, bear in mind that it will take some time (hours) for all mirrors to be fully updated.

**Comment by MyriaCore** [comment]
I don't mean to necropost or anything, but I'm still having this issue. I'm new to Linux, so I'm not super sure if it's something I'm doing, but context is the exact same for me, and the mirrors should be updated 3 days later.
